workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Esv-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/walker/esv/esv-org-api:main
        registry:
            location: registry.speakeasyapi.dev/walker/esv/esv-oas
targets:
    esv:
        target: php
        source: Esv-OAS
        publish:
            packagist:
                username: $packagist_username
                token: $packagist_token
