<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Esv\Models\Operations;

use Esv\Utils\SpeakeasyMetadata;
class GetPassageTextRequest
{
    /**
     * Bible passage reference (e.g., "John 3:16" or "43011016")
     *
     * @var string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=q')]
    public string $query;

    /**
     * Include passage references before passages
     *
     * @var ?bool $includePassageReferences
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-passage-references')]
    public ?bool $includePassageReferences = null;

    /**
     * Include verse numbers
     *
     * @var ?bool $includeVerseNumbers
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-verse-numbers')]
    public ?bool $includeVerseNumbers = null;

    /**
     * Include the verse number for the first verse of a chapter
     *
     * @var ?bool $includeFirstVerseNumbers
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-first-verse-numbers')]
    public ?bool $includeFirstVerseNumbers = null;

    /**
     * Include callouts to footnotes in the text.
     *
     * @var ?bool $includeFootnotes
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-footnotes')]
    public ?bool $includeFootnotes = null;

    /**
     * Include footnote body content
     *
     * @var ?bool $includeFootnoteBody
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-footnote-body')]
    public ?bool $includeFootnoteBody = null;

    /**
     * Include passage headings
     *
     * @var ?bool $includeHeadings
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-headings')]
    public ?bool $includeHeadings = null;

    /**
     * Include a short copyright notice
     *
     * @var ?bool $includeShortCopyright
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-short-copyright')]
    public ?bool $includeShortCopyright = null;

    /**
     * Include the full copyright notice
     *
     * @var ?bool $includeCopyright
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-copyright')]
    public ?bool $includeCopyright = null;

    /**
     * Include horizontal lines between passages
     *
     * @var ?bool $includePassageHorizontalLines
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-passage-horizontal-lines')]
    public ?bool $includePassageHorizontalLines = null;

    /**
     * Include horizontal lines under headings
     *
     * @var ?bool $includeHeadingHorizontalLines
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-heading-horizontal-lines')]
    public ?bool $includeHeadingHorizontalLines = null;

    /**
     * Length of horizontal lines
     *
     * @var ?int $horizontalLineLength
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=horizontal-line-length')]
    public ?int $horizontalLineLength = null;

    /**
     * Include "Selah" in passage text
     *
     * @var ?bool $includeSelahs
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-selahs')]
    public ?bool $includeSelahs = null;

    /**
     * Character to use for indentation
     *
     * @var ?IndentUsing $indentUsing
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=indent-using')]
    public ?IndentUsing $indentUsing = null;

    /**
     * Number of indentation characters for paragraphs
     *
     * @var ?int $indentParagraphs
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=indent-paragraphs')]
    public ?int $indentParagraphs = null;

    /**
     * Number of indentation characters for poetry
     *
     * @var ?int $indentPoetry
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=indent-poetry')]
    public ?int $indentPoetry = null;

    /**
     * Number of indentation characters for poetry lines
     *
     * @var ?int $indentPoetryLines
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=indent-poetry-lines')]
    public ?int $indentPoetryLines = null;

    /**
     * Number of indentation characters for declares
     *
     * @var ?int $indentDeclares
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=indent-declares')]
    public ?int $indentDeclares = null;

    /**
     * Number of indentation characters for Psalm doxology
     *
     * @var ?int $indentPsalmDoxology
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=indent-psalm-doxology')]
    public ?int $indentPsalmDoxology = null;

    /**
     * Maximum line length
     *
     * @var ?int $lineLength
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=line-length')]
    public ?int $lineLength = null;

    /**
     * @param  string  $query
     * @param  ?bool  $includePassageReferences
     * @param  ?bool  $includeVerseNumbers
     * @param  ?bool  $includeFirstVerseNumbers
     * @param  ?bool  $includeFootnotes
     * @param  ?bool  $includeFootnoteBody
     * @param  ?bool  $includeHeadings
     * @param  ?bool  $includeShortCopyright
     * @param  ?bool  $includeCopyright
     * @param  ?bool  $includePassageHorizontalLines
     * @param  ?bool  $includeHeadingHorizontalLines
     * @param  ?int  $horizontalLineLength
     * @param  ?bool  $includeSelahs
     * @param  ?IndentUsing  $indentUsing
     * @param  ?int  $indentParagraphs
     * @param  ?int  $indentPoetry
     * @param  ?int  $indentPoetryLines
     * @param  ?int  $indentDeclares
     * @param  ?int  $indentPsalmDoxology
     * @param  ?int  $lineLength
     * @phpstan-pure
     */
    public function __construct(string $query, ?bool $includePassageReferences = true, ?bool $includeVerseNumbers = true, ?bool $includeFirstVerseNumbers = true, ?bool $includeFootnotes = true, ?bool $includeFootnoteBody = true, ?bool $includeHeadings = true, ?bool $includeShortCopyright = false, ?bool $includeCopyright = false, ?bool $includePassageHorizontalLines = false, ?bool $includeHeadingHorizontalLines = false, ?int $horizontalLineLength = 55, ?bool $includeSelahs = true, ?IndentUsing $indentUsing = IndentUsing::Space, ?int $indentParagraphs = 2, ?int $indentPoetry = 2, ?int $indentPoetryLines = 4, ?int $indentDeclares = 40, ?int $indentPsalmDoxology = 30, ?int $lineLength = 0)
    {
        $this->query = $query;
        $this->includePassageReferences = $includePassageReferences;
        $this->includeVerseNumbers = $includeVerseNumbers;
        $this->includeFirstVerseNumbers = $includeFirstVerseNumbers;
        $this->includeFootnotes = $includeFootnotes;
        $this->includeFootnoteBody = $includeFootnoteBody;
        $this->includeHeadings = $includeHeadings;
        $this->includeShortCopyright = $includeShortCopyright;
        $this->includeCopyright = $includeCopyright;
        $this->includePassageHorizontalLines = $includePassageHorizontalLines;
        $this->includeHeadingHorizontalLines = $includeHeadingHorizontalLines;
        $this->horizontalLineLength = $horizontalLineLength;
        $this->includeSelahs = $includeSelahs;
        $this->indentUsing = $indentUsing;
        $this->indentParagraphs = $indentParagraphs;
        $this->indentPoetry = $indentPoetry;
        $this->indentPoetryLines = $indentPoetryLines;
        $this->indentDeclares = $indentDeclares;
        $this->indentPsalmDoxology = $indentPsalmDoxology;
        $this->lineLength = $lineLength;
    }
}