<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WalkerTx\Esv\Models\Operations;

use WalkerTx\Esv\Utils\SpeakeasyMetadata;
class GetPassageAudioRequest
{
    /**
     * Bible passage reference (e.g., "John 3:16" or "43011016")
     *
     * @var string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=q')]
    public string $query;

    /**
     * @param  string  $query
     * @phpstan-pure
     */
    public function __construct(string $query)
    {
        $this->query = $query;
    }
}