<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WalkerTx\Esv\Models\Operations;


/** Character to use for indentation */
enum IndentUsing: string
{
    case Space = 'space';
    case Tab = 'tab';
}
