<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Esv\Models\Operations;


/** SearchPassagesResponseBody - Successful response */
class SearchPassagesResponseBody
{
    /**
     * Current page number
     *
     * @var ?int $page
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('page')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $page = null;

    /**
     * Total number of pages
     *
     * @var ?int $totalPages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_pages')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $totalPages = null;

    /**
     * Total number of results
     *
     * @var ?int $totalResults
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_results')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $totalResults = null;

    /**
     * $results
     *
     * @var ?array<Results> $results
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('results')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Esv\Models\Operations\Results>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $results = null;

    /**
     * @param  ?int  $page
     * @param  ?int  $totalPages
     * @param  ?int  $totalResults
     * @param  ?array<Results>  $results
     * @phpstan-pure
     */
    public function __construct(?int $page = null, ?int $totalPages = null, ?int $totalResults = null, ?array $results = null)
    {
        $this->page = $page;
        $this->totalPages = $totalPages;
        $this->totalResults = $totalResults;
        $this->results = $results;
    }
}