<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WalkerTx\Esv\Models\Components;


class PassageResponse
{
    /**
     * The passage reference that was requested
     *
     * @var ?string $query
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('query')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $query = null;

    /**
     * The canonical version of the passage reference
     *
     * @var ?string $canonical
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canonical')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $canonical = null;

    /**
     * Array of parsed passage references
     *
     * @var ?array<array<int>> $parsed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parsed')]
    #[\Speakeasy\Serializer\Annotation\Type('array<array<int>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $parsed = null;

    /**
     * $passageMeta
     *
     * @var ?array<PassageMeta> $passageMeta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passage_meta')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\WalkerTx\Esv\Models\Components\PassageMeta>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passageMeta = null;

    /**
     * Array of formatted passage text
     *
     * @var ?array<string> $passages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passages')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passages = null;

    /**
     * @param  ?string  $query
     * @param  ?string  $canonical
     * @param  ?array<array<int>>  $parsed
     * @param  ?array<PassageMeta>  $passageMeta
     * @param  ?array<string>  $passages
     * @phpstan-pure
     */
    public function __construct(?string $query = null, ?string $canonical = null, ?array $parsed = null, ?array $passageMeta = null, ?array $passages = null)
    {
        $this->query = $query;
        $this->canonical = $canonical;
        $this->parsed = $parsed;
        $this->passageMeta = $passageMeta;
        $this->passages = $passages;
    }
}