<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Esv\Models\Components;

use Esv\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var string $apiKey
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=Authorization')]
    public string $apiKey;

    /**
     * @param  string  $apiKey
     * @phpstan-pure
     */
    public function __construct(string $apiKey)
    {
        $this->apiKey = $apiKey;
    }
}