<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Esv;



/**
 * Esv - ESV.org API: A convenient way to fetch content from ESV.org.
 *
 * The ESV API provides access to the ESV text, with a customizable presentation in  multiple formats. 
 * https://api.esv.org/ - ESV API Website
 *
 * @see https://api.esv.org/
 */
class Esv
{
    public const SERVERS = [
        /** Production server */
        'https://api.esv.org/v3/',
    ];

    public Passages $passages;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return EsvBuilder
     */
    public static function builder(): EsvBuilder
    {
        return new EsvBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->passages = new Passages($this->sdkConfiguration);
        $this->sdkConfiguration->client = $this->sdkConfiguration->initHooks($this->sdkConfiguration->client);

    }
}